version: '3.8'

volumes:
    exam_data:


services:
    adminer:
        container_name: adminer
        image: adminer:latest
        restart: unless-stopped
        ports:
            - 8080:8080

    mysql:
        container_name: exam-database
        image: mysql:8
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=exam
            - MYSQL_USER=local
            - MYSQL_PASSWORD=local
            - MYSQL_ROOT_PASSWORD=local
        volumes:
            - exam_data:/var/lib/mysql
